name: Bun

on:
  workflow_dispatch:
    inputs:
      push:
        description: push
        required: true
        default: true
        type: boolean
  push:
    branches:
      - main
    paths:
      - bun.dockerfile

env:
  REGISTRY_IMAGE: tsuk1ko/act-runner-images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        id: bun
        uses: oven-sh/setup-bun@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: bun.dockerfile
          push: ${{ github.event_name != 'workflow_dispatch' || inputs.push }}
          tags: ${{ env.REGISTRY_IMAGE }}:bun-latest ${{ env.REGISTRY_IMAGE }}:bun-${{ steps.bun.bun-version }}
          labels: ${{ steps.meta.outputs.labels }}
